using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TruckManagement.Enums;

namespace TruckManagement.Entities
{
    /// <summary>
    /// Represents a generated PDF version of a driver's employment contract.
    /// Supports full versioning and audit trail for contract changes over time.
    /// </summary>
    public class DriverContractVersion
    {
        /// <summary>
        /// Unique identifier for this contract version.
        /// </summary>
        [Key]
        public Guid Id { get; set; } = Guid.NewGuid();

        /// <summary>
        /// Foreign key to the Driver this contract belongs to.
        /// </summary>
        [Required]
        public Guid DriverId { get; set; }

        /// <summary>
        /// Navigation property to the Driver.
        /// </summary>
        [ForeignKey(nameof(DriverId))]
        public Driver Driver { get; set; } = default!;

        /// <summary>
        /// Foreign key to the EmployeeContract this PDF was generated from.
        /// </summary>
        [Required]
        public Guid EmployeeContractId { get; set; }

        /// <summary>
        /// Navigation property to the EmployeeContract.
        /// </summary>
        [ForeignKey(nameof(EmployeeContractId))]
        public EmployeeContract EmployeeContract { get; set; } = default!;

        /// <summary>
        /// Sequential version number for this driver (1, 2, 3, ...).
        /// Used to track contract iterations over time.
        /// </summary>
        [Required]
        public int VersionNumber { get; set; }

        /// <summary>
        /// Filename of the PDF stored in the filesystem.
        /// Example: "contract_v1_20251115_143022_a7b3c4d5.pdf"
        /// </summary>
        [Required]
        [MaxLength(255)]
        public string PdfFileName { get; set; } = default!;

        /// <summary>
        /// Full path to the PDF file in the filesystem.
        /// Example: "/storage/contracts/2025/11/driverId/contract_v1_20251115_143022.pdf"
        /// </summary>
        [Required]
        [MaxLength(500)]
        public string PdfFilePath { get; set; } = default!;

        /// <summary>
        /// Size of the PDF file in bytes.
        /// </summary>
        [Required]
        public long FileSize { get; set; }

        /// <summary>
        /// MIME type of the file (always "application/pdf").
        /// </summary>
        [Required]
        [MaxLength(100)]
        public string ContentType { get; set; } = "application/pdf";

        /// <summary>
        /// Timestamp when this contract version was generated (UTC).
        /// </summary>
        [Required]
        public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Foreign key to the user (customerAdmin or globalAdmin) who generated this contract.
        /// Nullable if generated by system/automated process.
        /// </summary>
        [MaxLength(450)]
        public string? GeneratedByUserId { get; set; }

        /// <summary>
        /// Navigation property to the user who generated this contract.
        /// </summary>
        [ForeignKey(nameof(GeneratedByUserId))]
        public ApplicationUser? GeneratedByUser { get; set; }

        /// <summary>
        /// JSON snapshot of the EmployeeContract data at the time of generation.
        /// This preserves the exact data that was used to create the PDF,
        /// even if the contract is later modified.
        /// Essential for audit trail and legal compliance.
        /// </summary>
        [Required]
        [Column(TypeName = "jsonb")]
        public string ContractDataSnapshot { get; set; } = "{}";

        /// <summary>
        /// Indicates if this is the most recent/current version for this driver.
        /// Only one version per driver should have IsLatestVersion = true.
        /// When a new version is created, previous versions are marked false.
        /// </summary>
        [Required]
        public bool IsLatestVersion { get; set; } = true;

        /// <summary>
        /// Current status of this contract in its lifecycle.
        /// </summary>
        [Required]
        public ContractVersionStatus Status { get; set; } = ContractVersionStatus.Generated;

        /// <summary>
        /// Optional notes about this contract version.
        /// Can be used to document why a new version was generated,
        /// or any special circumstances.
        /// </summary>
        [MaxLength(1000)]
        public string? Notes { get; set; }
    }
}

