name: Deploy Backend to Plesk Server with Docker Compose

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' 

      - name: Build the Solution
        run: |
          dotnet build --configuration Release
        working-directory: ./TruckManagement  # Update to your solution folder if needed

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy Files with rsync
        run: |
          rsync -av --progress \
            --exclude=".git" \
            --exclude=".idea" \
            . ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/vhosts/${{ secrets.SERVER_DOMAIN }}/

      - name: Rebuild and Restart Docker Containers
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
          
          # ① make sure the bind‑mount folder exists and is writable
          sudo mkdir -p /var/www/storage/signed-contracts &&
          sudo chmod -R 777 /var/www/storage/signed-contracts &&
            
          # ② redeploy the stack
          cd /var/www/vhosts/${{ secrets.SERVER_DOMAIN }}/ && \
          docker compose down && \
          dotnet clean && \
          docker compose build && \
          docker compose up -d
          "
